model:
  type: text
  num_classes: 1
  pretrained: bert-base-uncased
  max_length: 128
  trainable_bert: true

data:
  tsv_path: data/top5_memes_tidy.tsv
  binary_classes: [Scared Cat, Who Killed Hannibal]
  batch_size: 32
  val_size: 0.1
  test_size: 0.25
  seed: 15

training:
  optimizer: adam
  learning_rate: 3.0e-5
  epochs: 10
  early_stopping_patience: 3
  verbose: 2
